export const productos = [
    {
        id: 1,
        nombre: "Monitor",
        precio: 100,
        categoria: "computadora",
        stock: 10,
        descripcion: "El mejor monitor del mundo",
        img: "",
    },
    {
        id: 2,
        nombre: "Teclado",
        precio: 70,
        categoria: "computadora",
        stock: 12,
        descripcion: "Es mecánico",
        img: "",
    },
    {
        id: 3,
        nombre: "Funda de celular de Bokita",
        precio: 120,
        categoria: "celular",
        stock: 15,
        descripcion: "Esta funda es muy grande",
        img: "",
    },
    {
        id: 4,
        nombre: "Funda de celular de River",
        precio: 120,
        categoria: "celular",
        stock: 15,
        descripcion: "Funda solo apta para millonarios",
        img: "",
    },
];